name: yes_no_app_manuel_4sa
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_cors: ^1.5.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.2 
  dio: ^5.7.0
  intl: ^0.18.0

dev_dependencies:

  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
